### ISSUE TITLE
Home URL incorrect

### ISSUE THREAD

**Issue by oevna** [weDevsOfficial/wedocs-plugin#17]
The docs are displayed at /blog/docs and your breadcrumb function is using home_url('/') which is / instead of /blog/docs). How can this be resolved without editing your functions.php?

**Comment by tareq1988** [comment]
Home means the home page, not the docs home page!

**Comment by finalhit** [comment]
Home should be the home of documentation, it is related to plugin, not website.

In wedocs_breadcrumbs() function link to Home should be home_url( '/' . $slug . '/' ) instead of home_url( '/' ). Just have to fetch $slug somehow.

Solution for docs archive page is proposed at https://github.com/tareq1988/wedocs-plugin/issues/26
